orchestrator:
  # port: ${generate_port:orchestrator}
  port: 8081
  web_port: ${generate_port:orchestrator_web}
  # web_endpoint: http://localhost:${generate_port:orchestrator_web}
  web_endpoint: http://100.70.158.113:${generate_port:orchestrator_web}
  log_level: warning
trial_datastore:
  # port: ${generate_port:trial_datastore}
  port: 8082
  log_level: warning
model_registry:
  # port: ${generate_port:model_registry}
  port: 8083
  # web_endpoint: http://sample
  log_level: warning
web:
  port: 8080
  build: False
  dev: False
