defaults:
  - services: local_base_services
  - services/environment: lunar_lander
  - services/actor: random
  - run: play
  - _self_
  - experiment: simple_maddpg/simple_tag

hydra:
  job:
    name: ${run.class_name}
    id: ${run.run_id}
    num: 0
run:
  run_id: ${generate_name:run_id}_${hydra:job.num}
  # mlflow_tracking_uri: http://localhost:3000
  mlflow_tracking_uri: http://100.70.158.113:3000
