class_name: runs.play.PlayRun
observer: True
num_trials: 10
seed: 12
players:
  - name: player_1
    implementation: actors.random_actor.RandomActor
  - name: player_2
    implementation: actors.random_actor.RandomActor
