class_name: actors.simple_a2c.SimpleA2CTraining
environment_config:
  seed: 618
training:
  epoch_count: 500
  epoch_trial_count: 10
  num_parallel_trials: 8
  discount_factor: 0.95
  entropy_loss_coef: 0.05
  value_loss_coef: 0.5
  action_loss_coef: 1.0
  learning_rate: 0.01
actor_network:
  hidden_size: 64
critic_network:
  hidden_size": 64
